<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <!-- AWS SDK -->
    <PackageReference Include="AWSSDK.CloudWatchLogs" Version="3.7.410.17" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.402.35" />
    <PackageReference Include="AWSSDK.Rekognition" Version="3.7.400.129" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.416.5" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="3.7.404.10" />
    <!-- AWS Logging for NLog -->
    <PackageReference Include="AWS.Logger.NLog" Version="3.3.4" />
    <!-- NLog -->
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.14" />
    <!-- EF Core - SQL Server -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <!-- ASP.NET Core Authentication -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.5" />
    <!-- Newtonsoft -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Common\Bookstore.Common.csproj" />
    <ProjectReference Include="..\Bookstore.Data\Bookstore.Data.csproj" />
    <ProjectReference Include="..\Bookstore.Domain\Bookstore.Domain.csproj" />
  </ItemGroup>
</Project>
